git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers
customCommands:
  - key: "<c-r>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
  - key: "v"
    prompts:
      - type: 'input'
        title: 'PR id:'
    command: "gh pr checkout {{index .PromptResponses 0}}"
    context: "localBranches"
    loadingText: "checking out PR"
  - key: "v"
    context: "status"
    command: "gh repo view --web"
  - key: "x"
    context: "global"
    prompts:
      - type: 'input'
        title: 'Commit message'
    command: "git commit --allow-empty -m {{index .PromptResponses 0}}"
